### PR TITLE
Create base WordPress-specific ruleset

### PR DESCRIPTION
**Pull request by jeffpaul**
Based on @jrfnl's work: https://github.com/wimg/PHPCompatibility/issues/514#issuecomment-340369984
Further annotations for the ruleset.xml: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml

### CODE REVIEW

**Comment by jrfnl** [comment]
For the record - this isn't "based on" my work. It **_is_** 100% my work without any changes....

I would suggest you keep a close eye on wimg/PHPCompatibility#530 and contribute to the example rulesets in the PHPCompatibility repo as soon as they are added instead of maintaining your own.

**Comment by jeffpaul** [comment]
@jrfnl you are correct, this is your work, apologies that my comment was misleading. I had intended this as a message to those looking to contribute to this from the Tide project to use your work as a base and build off it by adding excludes/include as necessary from testing/feedback. Thank you for all your work without which Tide would have nothing to utilize!

In parallel, my reading of issues in https://github.com/wimg/PHPCompatibility seemed to point me toward maintaining a WordPress-specific ruleset here instead of in the wimg repo. Assuming you meant to say we should manage the WordPress-specific ruleset in the wimg repo, where should we begin contributing with a PR in the codebase there?

**Comment by jrfnl** [comment]
A PR has been opened in the PHPCompatibility library upstream which should take care of this: https://github.com/wimg/PHPCompatibility/pull/615

**Comment by jeffpaul** [comment]
Closing in favor of https://github.com/wimg/PHPCompatibility/pull/615

**Pull request closed without merging**
